Add links for lesson 1
ro31337/rubyschool pull request #54
Opened 2022-07-27 17:32 UTC by sas2job

2022-07-27 18:28 UTC, ro31337 requested changes
Надо написать, что не Linux Mint Cinnamon, а Linux Mint Cinnamon (English) - чтобы русскую не устанавливали. А то наши студенты любители русскую версию поставить

2022-07-27 18:35 UTC, denislituev commented on README.md
> +Если планируйте перейти на Linux то необходимо выбрать [Linux Mint Cinnamon](https://www.linuxmint.com/download.php)
Typo: ~~"планируйте"~~ -> "планируете"

2022-07-28 08:42 UTC, sas2job commented
> Надо написать, что не Linux Mint Cinnamon, а Linux Mint Cinnamon (English) - чтобы русскую не устанавливали. А то наши студенты любители русскую версию поставить

Пофиксил.

2022-07-28 08:42 UTC, sas2job commented on README.md
> +Если планируйте перейти на Linux то необходимо выбрать [Linux Mint Cinnamon](https://www.linuxmint.com/download.php)
> Typo: ~"планируйте"~ -> "планируете"
Ок

2022-07-28 12:36 UTC, denislituev approved these changes
looks good

2022-07-28 15:10 UTC, ro31337 commented
Запятую вот ещё забыли:

> Если планируете перейти на Linux то

должно быть

> Если планируете перейти на Linux, то

2022-07-28 15:15 UTC, sas2job commented
> Запятую вот ещё забыли:
> 
> > Если планируете перейти на Linux то
> 
> должно быть
> 
> > Если планируете перейти на Linux, то

Пофиксил.

2022-07-28 15:38 UTC, merged

2022-07-28 15:38 UTC, ro31337 commented
Спасибо